# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semirest', '0002_auto_20160815_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
